text:
	dc.b "            "
	dc.b "            "
	dc.b "   FLUSH    "
	dc.b " OFFER YOU  "
	dc.b "            "
	dc.b " QRASFATARI "
	dc.b "            "
	dc.b "DA ^K SPLIFF"
	dc.b "  ROLLED BY "
	dc.b "   FLEWWW   "
	dc.b " NQ GLAFOUK "
	dc.b "RELEASED FOR"
	dc.b "SHADOW PARTY"
	dc.b "        ][]\"
	dc.b "            "
	dc.b "  RULES OF  "
	dc.b "RASFATARISM_"
	dc.b "            "
	dc.b "RACE DA BEAM"
	dc.b "SMOKE DA TIA"
	dc.b "DRINK DA ROM"
	dc.b "FUCK DA BYTE"
	dc.b "            "
	dc.b "JAY BLESSING"
	dc.b "NQ BIG UP TO"
	dc.b "      ALTAIR"
	dc.b "    BOCK    "
	dc.b "CLUSTER     "
	dc.b "       COINE"
	dc.b "COOKIE CREW "
	dc.b "   DELICIOUS"
	dc.b "   AMIGANS  "
	dc.b "DENTIFRICE  "
	dc.b "         DMA"
	dc.b "DUNE        "
	dc.b "     GENESIS"
	dc.b "     PROJECT"
	dc.b "GOBLINISH   "
	dc.b "         JAC"
	dc.b " LABORATOIRE"
	dc.b " PROUT      "
	dc.b "   LAMERS   "
	dc.b "MYSTIC BYTES"
	dc.b "       NOICE"
	dc.b "PLANET JAZZ "
	dc.b "  POPSY TEAM"
	dc.b "RBBS        "
	dc.b "  RESISTANCE"
	dc.b "SATORI      "
	dc.b "  SECTOR ONE"
	dc.b "SHIRU       "
	dc.b "       SWYNG"
	dc.b "TENFOUR     "
	dc.b "         TMP"
	dc.b "TRILOBIT    "
	dc.b "     UNDEAD "
	dc.b "     SCENERS"
	dc.b "UP ROUGH    "
	dc.b "    ULTRASYD"
	dc.b "VITAL MOTION"
	dc.b "       WAMMA"
	dc.b "XAYAX       "
	dc.b "       X MEN"
	dc.b " NQ YOU ALL "
	dc.b "            "
	dc.b "TUFF NQ RUFF"
	dc.b " LIKE A VCS "
	dc.b "            "
	dc.b " QJAY BLESS "
	dc.b " RASFATARIQ "
	dc.b 0,"           "
	dc.b "            "
