text:
	dc.b "            "
	dc.b "            "
	dc.b "   FLUSH    "
	dc.b "  PRESENTS  "
	dc.b "  RASFATARI "
	dc.b "            "
	dc.b "AN ATARI VCS"
	dc.b "^K INTRO    "
	dc.b "RELEASED AT "
	dc.b "SHADOW PARTY"
	dc.b "        ][]\"
	dc.b "            "
	dc.b "][][QS CRAP "
	dc.b "BUT AT LEAST"
	dc.b "WE COULD PUT"
	dc.b "THOSE BITS  "
	dc.b "TOGETHER    "
	dc.b "ON OUR GOOD "
	dc.b "OLD MACHINE "
	dc.b "            "
	dc.b "  CREDITS   "
	dc.b "MSX NQ GFX  "
	dc.b "GLAFOUK     "
	dc.b "      CODE  "
	dc.b "      FLEWWW"
	dc.b "            "
	dc.b "GREETINGS   "
	dc.b "TO ALL THE  "
	dc.b "PEOP WE LOVE"
	dc.b "INCLUDING   "
	dc.b "BUT NOT     "
	dc.b "LIMITED TO  "
	dc.b "      ALTAIR"
	dc.b "CLUSTER     "
	dc.b "       COINE"
	dc.b "COOKIE CREW "
	dc.b "   DELICIOUS"
	dc.b "   AMIGANS  "
	dc.b "DENTIFRICE  "
	dc.b "         DMA"
	dc.b "DUNE        "
	dc.b "     GENESIS"
	dc.b "     PROJECT"
	dc.b "GOBLINISH   "
	dc.b "         JAC"
	dc.b " LABORATOIRE"
	dc.b " PROUT      "
	dc.b "MYSTIC BYTES"
	dc.b "       NOICE"
	dc.b "PLANET JAZZ "
	dc.b "  POPSY TEAM"
	dc.b "RBBS        "
	dc.b "  RESISTANCE"
	dc.b "SECTOR ONE  "
	dc.b "       SWYNG"
	dc.b "TENFOUR     "
	dc.b "         TMP"
	dc.b "TRILOBIT    "
	dc.b "     UNDEAD "
	dc.b "     SCENERS"
	dc.b "UP ROUGH    "
	dc.b "    ULTRASYD"
	dc.b "VITAL MOTION"
	dc.b "       WAMMA"
	dc.b "XAYAX       "
	dc.b "       X MEN"
	dc.b "   AND YOU  "
	dc.b 0,"           "
	dc.b "            "
